UASG_Project/urls.py
from django import views
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('discussionforum/', include('Discussion_Forum.urls')),
    path('applicationshowcase/', include('Application_Showcase.urls')),
    path('helpdesk/', include('Helpdesk.urls')),
    path('user/', include('User.urls')),



    path('viewdocuments', views.viewdocuments, name='viewdocuments'),
    path('accounts/', include('allauth.urls'))
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

User/urls.py
from django.urls import path
from . import views

app_name='User'

urlpatterns = [   
    path('',views.index,name="index" ),
    path('login',views.login,name="login"),
    path('register', views.register, name="register"),
    path('uploaddocumenthub',views.documenthub, name="documenthub"),
    path('datatable',views.datatable, name="datatable"),
    path('logout', views.logout, name="logout"),

]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Test</title>
    <script type="text/javascript">
      window.history.forward();
      function noBack() { window.history.forward(); }
    </script>
    <!-- CSS only -->
    <!-- Bootstrap Source Minified File -->
    <script src="{% static 'js/jquery-3.5.1.js' %}"></script>
    <script src="{% static 'js/datatables.js' %}"></script>
    <script src="{% static 'js/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'js/dataTables.bootstrap5.min.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"/> 
    <link rel="stylesheet" href="{% static 'css/bootstrapdatatable.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/dataTables.bootstrap5.min.css' %}"/>
    <link href="{% static 'css/bootstrap.min.css.map' %}"/>


    {% comment %} <script src="https://code.jquery.com/jquery-3.5.1.js"></script> {% endcomment %}
    {% comment %} <script src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script> {% endcomment %}
    {% comment %} <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.3/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.12.1/css/dataTables.bootstrap5.min.css"> {% endcomment %}
    {% comment %} <script type="text/javascript" src="{% static 'js/bootstrap.bundle.min.js' %}" crossorigin="anonymous"></script>  {% endcomment %}
    {% comment %} <script src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>  {% endcomment %}

    <link rel="stylesheet" href="{% static 'base.css' %}" />
  </head>
  <body>
    <header>
      <nav class="navbar">
        <ul>
          <li><a href="{% url 'home'%}">Home</a></li>
          <li><a href="{% url 'viewdocuments'%}">View Document</a></li>
          
          {{ user.is_authenticated }}

          {% if user.is_authenticated %}
          <li><a href="{% url 'User:documenthub'%}">Upload Document</a></li>
          <li><a href="{% url 'User:logout'%}">Logout</a></li> 
          {% else %}
          <li><a href="{% url 'User:register'%}">Register</a></li>
          <li><a href="{% url 'User:login'%}">Login</a></li>
          {% endif %}

         
       
        </ul>
      </nav>
        <div>
            {% if user.is_authenticated %}
              <p>welcome, {{ user.username }}</p>
            {% endif %}
        </div>
    </header>

    {% block home %} {% endblock %}
    
    {% block login %} 

    {% endblock %}

    {% block register %} 

    {% endblock %}

    {% block discussionforum %}

    {% endblock %}

    {% block documenthub %}

    {% endblock %}

    {% block documenthubview %}

    {% endblock %}


    {% block datatable %}

    {% endblock %}


    {% comment %} <script>
      $(document).ready(function () {
        $('#example').DataTable(
            {
                
                ordering:true,
                scrollY:'200px',
                scrollCollapse:true,
                order:[[3,'desc']],
                
            }
        );
    });
    </script>  {% endcomment %}
  </body>
</html>

templates/blogs.html
blogs

templates/casestudies.html
casestudies

templates/community.html
community

templates/contactus.html
contactus

templates/datatable.html
{% extends 'base.html' %}
{% load static %}
{% block datatable %}

<table id="example" class="table table-striped" style="width:100%">
    <thead>
        <tr>
            <th>Name</th>
            <th>Position</th>
            <th>Office</th>
            <th>Age</th>
            <th>Start date</th>
            <th>Salary</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>Tiger Nixon</td>
            <td>System Architect</td>
            <td>Edinburgh</td>
            <td>61</td>
            <td>2011-04-25</td>
            <td>$320,800</td>
        </tr>
        <tr>
            <td>Hermione Butler</td>
            <td>Regional Director</td>
            <td>London</td>
            <td>47</td>
            <td>2011-03-21</td>
            <td>$356,250</td>
        </tr>
        <tr>
            <td>Lael Greer</td>
            <td>Systems Administrator</td>
            <td>London</td>
            <td>21</td>
            <td>2009-02-27</td>
            <td>$103,500</td>
        </tr>
        <tr>
            <td>Jonas Alexander</td>
            <td>Developer</td>
            <td>San Francisco</td>
            <td>30</td>
            <td>2010-07-14</td>
            <td>$86,500</td>
        </tr>
        <tr>
            <td>Shad Decker</td>
            <td>Regional Director</td>
            <td>Edinburgh</td>
            <td>51</td>
            <td>2008-11-13</td>
            <td>$183,000</td>
        </tr>
        <tr>
            <td>Michael Bruce</td>
            <td>Javascript Developer</td>
            <td>Singapore</td>
            <td>29</td>
            <td>2011-06-27</td>
            <td>$183,000</td>
        </tr>
        <tr>
            <td>Donna Snider</td>
            <td>Customer Support</td>
            <td>New York</td>
            <td>27</td>
            <td>2011-01-25</td>
            <td>$112,000</td>
        </tr>
  
   
        
        <tr>
            <td>Tiger Nixon</td>
            <td>System Architect</td>
            <td>Edinburgh</td>
            <td>61</td>
            <td>2011-04-25</td>
            <td>$320,800</td>
        </tr>
        <tr>
            <td>Hermione Butler</td>
            <td>Regional Director</td>
            <td>London</td>
            <td>47</td>
            <td>2011-03-21</td>
            <td>$356,250</td>
        </tr>
        <tr>
            <td>Lael Greer</td>
            <td>Systems Administrator</td>
            <td>London</td>
            <td>21</td>
            <td>2009-02-27</td>
            <td>$103,500</td>
        </tr>
        <tr>
            <td>Jonas Alexander</td>
            <td>Developer</td>
            <td>San Francisco</td>
            <td>30</td>
            <td>2010-07-14</td>
            <td>$86,500</td>
        </tr>
        <tr>
            <td>Shad Decker</td>
            <td>Regional Director</td>
            <td>Edinburgh</td>
            <td>51</td>
            <td>2008-11-13</td>
            <td>$183,000</td>
        </tr>
        <tr>
            <td>Tiger Nixon</td>
            <td>System Architect</td>
            <td>Edinburgh</td>
            <td>61</td>
            <td>2011-04-25</td>
            <td>$320,800</td>
        </tr>
        <tr>
            <td>Hermione Butler</td>
            <td>Regional Director</td>
            <td>London</td>
            <td>47</td>
            <td>2011-03-21</td>
            <td>$356,250</td>
        </tr>
        <tr>
            <td>Lael Greer</td>
            <td>Systems Administrator</td>
            <td>London</td>
            <td>21</td>
            <td>2009-02-27</td>
            <td>$103,500</td>
        </tr>
        <tr>
            <td>Jonas Alexander</td>
            <td>Developer</td>
            <td>San Francisco</td>
            <td>30</td>
            <td>2010-07-14</td>
            <td>$86,500</td>
        </tr>
        <tr>
            <td>Shad Decker</td>
            <td>Regional Director</td>
            <td>Edinburgh</td>
            <td>51</td>
            <td>2008-11-13</td>
            <td>$183,000</td>
        </tr>
        <tr>
            <td>Tiger Nixon</td>
            <td>System Architect</td>
            <td>Edinburgh</td>
            <td>61</td>
            <td>2011-04-25</td>
            <td>$320,800</td>
        </tr>
        <tr>
            <td>Hermione Butler</td>
            <td>Regional Director</td>
            <td>London</td>
            <td>47</td>
            <td>2011-03-21</td>
            <td>$356,250</td>
        </tr>
        <tr>
            <td>Lael Greer</td>
            <td>Systems Administrator</td>
            <td>London</td>
            <td>21</td>
            <td>2009-02-27</td>
            <td>$103,500</td>
        </tr>
        <tr>
            <td>Jonas Alexander</td>
            <td>Developer</td>
            <td>San Francisco</td>
            <td>30</td>
            <td>2010-07-14</td>
            <td>$86,500</td>
        </tr>
        <tr>
            <td>Shad Decker</td>
            <td>Regional Director</td>
            <td>Edinburgh</td>
            <td>51</td>
            <td>2008-11-13</td>
            <td>$183,000</td>
        </tr>
        <tr>
            <td>Tiger Nixon</td>
            <td>System Architect</td>
            <td>Edinburgh</td>
            <td>61</td>
            <td>2011-04-25</td>
            <td>$320,800</td>
        </tr>
        <tr>
            <td>Hermione Butler</td>
            <td>Regional Director</td>
            <td>London</td>
            <td>47</td>
            <td>2011-03-21</td>
            <td>$356,250</td>
        </tr>
        <tr>
            <td>Lael Greer</td>
            <td>Systems Administrator</td>
            <td>London</td>
            <td>21</td>
            <td>2009-02-27</td>
            <td>$103,500</td>
        </tr>
        <tr>
            <td>Jonas Alexander</td>
            <td>Developer</td>
            <td>San Francisco</td>
            <td>30</td>
            <td>2010-07-14</td>
            <td>$86,500</td>
        </tr>
        <tr>
            <td>Shad Decker</td>
            <td>Regional Director</td>
            <td>Edinburgh</td>
            <td>51</td>
            <td>2008-11-13</td>
            <td>$183,000</td>
        </tr>
        <tr>
            <td>Tiger Nixon</td>
            <td>System Architect</td>
            <td>Edinburgh</td>
            <td>61</td>
            <td>2011-04-25</td>
            <td>$320,800</td>
        </tr>
        <tr>
            <td>Hermione Butler</td>
            <td>Regional Director</td>
            <td>London</td>
            <td>47</td>
            <td>2011-03-21</td>
            <td>$356,250</td>
        </tr>
        <tr>
            <td>Lael Greer</td>
            <td>Systems Administrator</td>
            <td>London</td>
            <td>21</td>
            <td>2009-02-27</td>
            <td>$103,500</td>
        </tr>
        <tr>
            <td>Jonas Alexander</td>
            <td>Developer</td>
            <td>San Francisco</td>
            <td>30</td>
            <td>2010-07-14</td>
            <td>$86,500</td>
        </tr>
        <tr>
            <td>Shad Decker</td>
            <td>Regional Director</td>
            <td>Edinburgh</td>
            <td>51</td>
            <td>2008-11-13</td>
            <td>$183,000</td>
        </tr>
        <tr>
            <td>Tiger Nixon</td>
            <td>System Architect</td>
            <td>Edinburgh</td>
            <td>61</td>
            <td>2011-04-25</td>
            <td>$320,800</td>
        </tr>
        <tr>
            <td>Hermione Butler</td>
            <td>Regional Director</td>
            <td>London</td>
            <td>47</td>
            <td>2011-03-21</td>
            <td>$356,250</td>
        </tr>
        <tr>
            <td>Lael Greer</td>
            <td>Systems Administrator</td>
            <td>London</td>
            <td>21</td>
            <td>2009-02-27</td>
            <td>$103,500</td>
        </tr>
        <tr>
            <td>Jonas Alexander</td>
            <td>Developer</td>
            <td>San Francisco</td>
            <td>30</td>
            <td>2010-07-14</td>
            <td>$86,500</td>
        </tr>
        <tr>
            <td>Shad Decker</td>
            <td>Regional Director</td>
            <td>Edinburgh</td>
            <td>51</td>
            <td>2008-11-13</td>
            <td>$183,000</td>
        </tr>
    </tbody>
</table>

{% endblock %}

templates/dialogueforum.html
dialogue forum

templates/documenthub.html
{% extends 'base.html' %}
{% load static %}
{% block documenthubview %}





{% for data in DocumentHub_Data %}
      

       <p>{{ data.DocumentHubData_Title }}</p>
       <p>{{ data.DocumentHubData_CategoryType }}</p>
       <p>{{ data.DocumentHubData_Tags }}</p>
       <p>{{ data.DocumentHubData_PublishedDate }}</p>
       <p>{{ data.DocumentHubData_CreationDate }}</p>
       <p>{{ data.DocumentHubData_FileSize }}</p>
       <p>{{ data.DocumentHubData_LastUpdatedDate }}</p>
       <p>{{ data.DocumentHubData_UploadSupportDocument }}</p>
       <p>{{ data.DocumentHubData_DownloadCounter }}</p>
       <p>{{ data.DocumentHubData_PublishedStatus }}</p>
       <p>{{ data.DocumentHubData_Languages }}</p>
       <p>{{ data.DocumentHubData_Author }}</p>


{% endfor %}




{% endblock %}

templates/home.html
{% extends 'base.html' %} {% block 'home' %}
<h2>Welcome To Test Portal</h2>
{% if user.is_authenticated %}
        <p>welcome, {{ user.username }}</p>
{% endif %}
<p>
  test
</p>
{% endblock %}

templates/news.html
news

templates/services.html
services

templates/termsandconditions.html
terms and conditions

templates/uacompliant.html
uacompliant

templates/uasgworkinggroup.html
uasg working group